name: Deploy Docs
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and deploy documentation from'
        required: true
        default: 'master'

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set variables
        run: |
          DOCS_REF="${{ github.event.inputs.branch }}"
          if [ -z "$DOCS_REF" ]; then
            DOCS_REF="${GITHUB_REF_NAME}"
          fi
          echo "DOCS_REF=$DOCS_REF" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "REPO_OWNER=${GITHUB_REPOSITORY%%/*}" >> $GITHUB_ENV
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Pull docs repository
        uses: actions/checkout@v4
        with:
          repository: moonbeam-foundation/moonbeam-docs
          ref: ${{ env.DOCS_REF }}
          path: moonbeam-docs
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.18
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential
      - name: Install pip requirements
        run: |
          # upgrade pip
          python -m pip install --upgrade pip setuptools 'cython<3.0.0' wheel
          # install dependencies quietly
          python -m pip install -r requirements.txt
      - name: Update image paths in Markdown files
        run: |
          # Replace old image paths with new paths in Markdown files
          find moonbeam-docs -type f -name "*.md" -exec sed -i -e "s|](/|](/${REPO_NAME}/|g" -e "s|href=\"/|href=\"/${REPO_NAME}/|g" {} \;
      - name: Replace `/assets` with `assets`
        run: |
          find . -type f -exec sed -i 's|/assets|assets|g' {} +
      - name: Set site_url for GitHub Pages base path
        run: |
          BASE_URL="https://${REPO_OWNER}.github.io/${REPO_NAME}/"
          sed -i "s#^site_url:.*#site_url: ${BASE_URL}#" mkdocs.yml
      - name: Deploy Docs
        run: mkdocs gh-deploy --force --clean --site-dir ./site
